# Generated by scripts/update_homebrew.py after a successful release.
class JustTalk < Formula
  desc "Desktop voice input with global hotkeys and streaming ASR"
  homepage "https://github.com/Aono255/just-talk-go"
  version "0.1.4"
  license "GPL-3.0-only"

  depends_on macos: :sequoia

  on_arm do
    url "https://github.com/Aono255/just-talk-go/releases/download/v0.1.4/just-talk_darwin_arm64.tar.gz"
    sha256 "fafbdb2a08fe896d08c080ce0a7b2ad7cb14f2122d11d8cde5ac585938ad83e4"
  end

  on_intel do
    url "https://github.com/Aono255/just-talk-go/releases/download/v0.1.4/just-talk_darwin_amd64.tar.gz"
    sha256 "25b56b7b196f038b4ae8d19dd46ec434a121fae02debcd86844232970f86ae0e"
  end

  def install
    bin.install "just-talk"
  end

  def caveats
    <<~EOS
      Grant Accessibility and Microphone permissions to the terminal app
      that launches just-talk. Configure Doubao ASR credentials via the TUI
      or ~/.config/just-talk/config.toml.
    EOS
  end

  test do
    assert_match "just-talk v#{version}", shell_output("#{(bin/"just-talk").to_s.shellescape} --version")
  end
end
