# Generated by scripts/update_homebrew.py after a successful release.
class JustTalk < Formula
  desc "Desktop voice input with global hotkeys and streaming ASR"
  homepage "https://github.com/Aono255/just-talk-go"
  version "0.1.9"
  license "GPL-3.0-only"

  depends_on macos: :sequoia

  on_arm do
    url "https://github.com/Aono255/just-talk-go/releases/download/v0.1.9/just-talk_darwin_arm64.tar.gz"
    sha256 "3dd383e8764704dbf3f77d282281b73553b39e13a2069dd84263ae2b65012b09"
  end

  on_intel do
    url "https://github.com/Aono255/just-talk-go/releases/download/v0.1.9/just-talk_darwin_amd64.tar.gz"
    sha256 "8515ac63f0663c149828e5e112b8a3a9017c741af88d127b874d24fb7133fe0e"
  end

  def install
    bin.install "just-talk"
  end

  def caveats
    <<~EOS
      Grant Accessibility and Microphone permissions to the terminal app
      that launches just-talk. Configure Doubao ASR credentials via the TUI
      or ~/.config/just-talk/config.toml.
    EOS
  end

  test do
    assert_match "just-talk v#{version}", shell_output("#{(bin/"just-talk").to_s.shellescape} --version")
  end
end
