# Generated by scripts/update_homebrew.py after a successful release.
class JustTalk < Formula
  desc "Desktop voice input with global hotkeys and streaming ASR"
  homepage "https://github.com/Aono255/just-talk-go"
  version "0.1.6"
  license "GPL-3.0-only"

  depends_on macos: :sequoia

  on_arm do
    url "https://github.com/Aono255/just-talk-go/releases/download/v0.1.6/just-talk_darwin_arm64.tar.gz"
    sha256 "79d98ac9d8242f12302d58a6d35ce8f02e44316560d3a9c8fe58911e49f08841"
  end

  on_intel do
    url "https://github.com/Aono255/just-talk-go/releases/download/v0.1.6/just-talk_darwin_amd64.tar.gz"
    sha256 "f75671c80524d04848b9bb8c10cfcf4e14d214d31b5a5bfea8f155c90ad466d1"
  end

  def install
    bin.install "just-talk"
  end

  def caveats
    <<~EOS
      Grant Accessibility and Microphone permissions to the terminal app
      that launches just-talk. Configure Doubao ASR credentials via the TUI
      or ~/.config/just-talk/config.toml.
    EOS
  end

  test do
    assert_match "just-talk v#{version}", shell_output("#{(bin/"just-talk").to_s.shellescape} --version")
  end
end
