#!/usr/bin/env python3
"""Update the macOS formula after a successful release, using its real checksums."""

import re
import sys
from pathlib import Path


def main():
    tag, checksum_file = sys.argv[1:]
    if not re.fullmatch(r"v\d+\.\d+\.\d+", tag):
        raise ValueError("Homebrew releases require a stable vMAJOR.MINOR.PATCH tag")
    checksums = {}
    for line in Path(checksum_file).read_text().splitlines():
        digest, name = line.split()
        if not re.fullmatch(r"[0-9a-f]{64}", digest) or name in checksums:
            raise ValueError(f"Invalid or duplicate checksum: {name}")
        checksums[name] = digest
    arm = checksums["just-talk_darwin_arm64.tar.gz"]
    intel = checksums["just-talk_darwin_amd64.tar.gz"]
    formula = f'''# Generated by scripts/update_homebrew.py after a successful release.
class JustTalk < Formula
  desc "Desktop voice input with global hotkeys and streaming ASR"
  homepage "https://github.com/Aono255/just-talk-go"
  version "{tag[1:]}"
  license "GPL-3.0-only"

  depends_on :macos

  on_arm do
    url "https://github.com/Aono255/just-talk-go/releases/download/{tag}/just-talk_darwin_arm64.tar.gz"
    sha256 "{arm}"
  end

  on_intel do
    url "https://github.com/Aono255/just-talk-go/releases/download/{tag}/just-talk_darwin_amd64.tar.gz"
    sha256 "{intel}"
  end

  def install
    bin.install "just-talk"
  end

  def caveats
    <<~EOS
      Grant Accessibility and Microphone permissions to the terminal app
      that launches just-talk. Configure Doubao ASR credentials via the TUI
      or ~/.config/just-talk/config.toml.
    EOS
  end

  test do
    assert_match "just-talk v#{{version}}", shell_output("#{{bin}}/just-talk --version")
  end
end
'''
    target = Path(__file__).resolve().parents[1] / "Formula" / "just-talk.rb"
    target.parent.mkdir(exist_ok=True)
    target.write_text(formula)


if __name__ == "__main__":
    main()
