#!/usr/bin/env bash
# Render Formula/just-talk.rb for the Homebrew tap.
#
# Inputs (environment):
#   TAG            release tag, e.g. v1.2.3 (required)
#   REPO           GitHub "owner/repo" that hosts the release (required)
#   SUMS_FILE      path to SHA256SUMS.txt from the release (required)
#   OUTPUT         file to write; defaults to Formula/just-talk.rb
set -euo pipefail

TAG="${TAG:?TAG is required, e.g. v1.2.3}"
REPO="${REPO:?REPO is required, e.g. wakaka6/just-talk-go}"
SUMS_FILE="${SUMS_FILE:?SUMS_FILE is required, path to SHA256SUMS.txt}"
OUTPUT="${OUTPUT:-Formula/just-talk.rb}"

sha256_for() {
  # Format produced by goreleaser: "<sha256>  <name>" (name may be path-prefixed).
  local file="$1" sum
  sum="$(awk -v f="$file" '{n=$2; sub(/.*\//, "", n); if (n == f) print $1}' "$SUMS_FILE")"
  if [ -z "$sum" ]; then
    echo "error: no sha256 for $file in $SUMS_FILE" >&2
    exit 1
  fi
  printf '%s' "$sum"
}

DARWIN_AMD64_SHA="$(sha256_for just-talk_darwin_amd64.tar.gz)"
DARWIN_ARM64_SHA="$(sha256_for just-talk_darwin_arm64.tar.gz)"
LINUX_AMD64_SHA="$(sha256_for just-talk_linux_amd64.tar.gz)"
LINUX_ARM64_SHA="$(sha256_for just-talk_linux_arm64.tar.gz)"

mkdir -p "$(dirname "$OUTPUT")"
cat > "$OUTPUT" <<EOF
# This file is generated by the release workflow of ${REPO}.
# Do not edit by hand in the tap repository.
class JustTalk < Formula
  desc "Desktop voice input: global hotkey, streaming ASR, paste into the focused field"
  homepage "https://github.com/${REPO}"
  license "GPL-3.0-only"

  # The archives wrap the binary in a just-talk_<os>_<arch>/ directory.
  on_macos do
    on_arm do
      url "https://github.com/${REPO}/releases/download/${TAG}/just-talk_darwin_arm64.tar.gz"
      sha256 "${DARWIN_ARM64_SHA}"
    end

    on_intel do
      url "https://github.com/${REPO}/releases/download/${TAG}/just-talk_darwin_amd64.tar.gz"
      sha256 "${DARWIN_AMD64_SHA}"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/${REPO}/releases/download/${TAG}/just-talk_linux_arm64.tar.gz"
      sha256 "${LINUX_ARM64_SHA}"
    end

    on_intel do
      url "https://github.com/${REPO}/releases/download/${TAG}/just-talk_linux_amd64.tar.gz"
      sha256 "${LINUX_AMD64_SHA}"
    end

    # The cgo build links these X11/Wayland libraries at runtime.
    depends_on "libx11"
    depends_on "libxext"
    depends_on "libxinerama"
    depends_on "libxrender"
    depends_on "libxtst"
    depends_on "wayland"
  end

  def install
    bin.install Dir.glob("just-talk_*/just-talk").first || "just-talk"
  end

  def caveats
    if OS.mac?
      <<~EOS
        just-talk needs permission granted to the terminal app that launches it
        (Terminal, iTerm2, etc.):

          * Accessibility: System Settings > Privacy & Security > Accessibility
          * Microphone:    System Settings > Privacy & Security > Microphone

        Configure your Doubao/Volcengine ASR credentials in
        ~/.config/just-talk/config.toml ([voice] app_key / access_key) or via the TUI.
      EOS
    else
      <<~EOS
        just-talk needs a running X11 or Wayland session (\$DISPLAY or
        \$WAYLAND_DISPLAY); global hotkeys may also need compositor/portal
        permission depending on your desktop environment.

        Configure your Doubao/Volcengine ASR credentials in
        ~/.config/just-talk/config.toml ([voice] app_key / access_key) or via the TUI.
      EOS
    end
  end

  test do
    # There is no --version flag; --help proves the binary runs (flag package exits 0).
    assert_match "Usage of", shell_output("#{bin}/just-talk --help 2>&1")
  end
end
EOF
echo "wrote $OUTPUT (darwin/arm64 ${DARWIN_ARM64_SHA}, darwin/amd64 ${DARWIN_AMD64_SHA}, linux/arm64 ${LINUX_ARM64_SHA}, linux/amd64 ${LINUX_AMD64_SHA})"
